const { faker } = require("@faker-js/faker");
const { Todo } = require("../server/db");


async function todoSeed() {
  const todos = await Promise.all([
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Do something nice for someone I care about",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Go to the gym",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Clean emotional support waterbottle",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Water plants",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Fold and put away laundry",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Plan a trip to another country",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Have a photo session with some friends",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Take dog on a walk",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Learn calligraphy",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Make own LEGO creation",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Learn Express.js",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Improve touch typing",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Create a compost pile",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Clean out car",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Organize pantry",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Text a friend",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Have a football scrimmage with some friends",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Invite some friends over for a game night",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Write a thank you letter",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Go see a Broadway production",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Bake pastries for me and neighbor",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Solve a Rubik's cube",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Contribute code or a monetary donation to an open-source software project",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Watch a classic movie",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Memorize the fifty states and their capitals",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Do something nice for someone I care about",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Go to the gym",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Clean emotional support waterbottle",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Water plants",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Fold and put away laundry",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Plan a trip to another country",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Have a photo session with some friends",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Take dog on a walk",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Learn calligraphy",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Make own LEGO creation",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Learn Express.js",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Improve touch typing",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Create a compost pile",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Clean out car",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Organize pantry",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Text a friend",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Have a football scrimmage with some friends",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Invite some friends over for a game night",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Write a thank you letter",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Go see a Broadway production",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Bake pastries for me and neighbor",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Solve a Rubik's cube",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Contribute code or a monetary donation to an open-source software project",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Watch a classic movie",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
    Todo.create({
      dueDate: faker.date.soon(14),
      todoName: "Memorize the fifty states and their capitals",
      pointType: faker.helpers.arrayElement(["important", "average"], 1),
      isCompleted: faker.datatype.boolean(),
      userId: faker.datatype.number({ min: 1, max: 20 }),
    }),
  ]);
  return { todos };
}
module.exports = todoSeed;